function output = muacceptratio(Ur, Vr, mur, mur_prop, murp, murm, ...
    a, b, c, K, L)
% compute the MH acceptance ratio
% Tess in samplemu.m
% Ur = U(:, r); Vr = V(:, r);
% mur = mu(r, :); murp = mu(r + 1, :); murm = mu(r - 1, :);

    output = min(1, UV_mupdf(Ur, Vr, mur_prop(1), mur_prop(2)) / ...
        UV_mupdf(Ur, Vr, mur(1), mur(2)) * ...
        mucondpdf(mur_prop, murp, murm, a, b, c) / ...
        mucondpdf(mur, murp, murm, a, b, c) * ...
        mucondproppdf(mur, murp, murm, a, b, c, K, L) / ...
        mucondproppdf(mur_prop, murp, murm, a, b, c, K, L));
end