function output = UV_mupdf(Ur, Vr, muru, murv)
% ProbUV_mu - compute the probability Pr(U, V | \mu) in Eq. (2.20)
% the probability of the r columns of U and V generated by muru and murv

% Todo:
%   - verify the consistency of -1

    % Check if Ur and Vr exist.
    % If not, use marginal density
    if ~strcmp(Ur, 'none') && ~strcmp(Vr, 'none')
        I = length(Ur);
        J = length(Vr);
        
        output = muru^sum(Ur) * (1 - muru)^(I - sum(Ur)) * ...
            murv^sum(Vr) * (1 - murv)^(J - sum(Vr));
    elseif ~strcmp(Ur, 'none') && strcmp(Vr, 'none')
        I = length(Ur);
        output = muru^sum(Ur) * (1 - muru)^(I - sum(Ur));        
    elseif strcmp(Ur, 'none') && ~strcmp(Vr, 'none')
        J = length(Vr);
        output =  murv^sum(Vr) * (1 - murv)^(J - sum(Vr));
    end
end

